import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div className="h-screen w-screen flex flex-col">
      <Head>
        <title>New App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello World!</h1>
      <h1>Hello World!</h1>
    </div>
  );
};

export default Home;
